src/Entity/Message.php
<?php

namespace App\Entity;

use App\Entity\User;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\MessageRepository;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=MessageRepository::class)
 * @Vich\Uploadable
 */
class Message
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="messagefrom")
     * @ORM\JoinColumn(nullable=false)
     */
    private $from_id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="messageto")
     * @ORM\JoinColumn(nullable=false)
     */
    private $to_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $subject;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isRead;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cv;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fichier;

    /**
     * @Vich\UploadableField(mapping="product_images", fileNameProperty="fichier")
     * @var File
     */
    private $fichierFile;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFromId(): ?User
    {
        return $this->from_id;
    }

    public function setFromId(?User $from_id): self
    {
        $this->from_id = $from_id;

        return $this;
    }

    public function getToId(): ?User
    {
        return $this->to_id;
    }

    public function setToId(?User $to_id): self
    {
        $this->to_id = $to_id;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->isRead;
    }

    public function setIsRead(?bool $isRead): self
    {
        $this->isRead = $isRead;

        return $this;
    }

    public function getCv(): ?string
    {
        return $this->cv;
    }

    public function setCv(?string $cv): self
    {
        $this->cv = $cv;

        return $this;
    }

    // Upload fichier

    public function setFichierFile(File $fichier = null)
    {
        $this->fichierFile = $fichier;
    }
 
    public function getFichierFile()
    {
        return $this->fichierFile;
    }

    public function setFichier($fichier)
    {
        $this->fichier = $fichier;

    }

    public function getFichier()
    {
        return $this->fichier;
    }

}

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Message;
use App\Repository\UserRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Security\Core\Security;
use Vich\UploaderBundle\Form\Type\VichFileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Mapping\Annotation\Uploadable;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;


class MessageType extends AbstractType
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;

    }
    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('to_id', EntityType::class, [
                'label' => 'Destinataire',
                'class' => User::class,
                'query_builder' => function (UserRepository $er) {
                    $user = $this->security->getUser();
                    return $er->sender($user); },])
            ->add('subject', TextType::class, [
                'label' => 'Sujet'
            ])
            ->add('content', TextareaType::class, [
                'label' => 'Message'
            ])
            ->add('fichierFile', VichFileType::class, [
                'required' => false,
                'label' => 'Fichier'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use App\Classe\Mail;
use App\Entity\User;
use App\Entity\Message;
use App\Form\MessageType;
use App\Form\ReplyMessageType;
use App\Repository\UserRepository;
use App\Repository\MessageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

/**
 * @Route("/message")
 */
class MessageController extends AbstractController
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }
    
    /**
     * @Route("/", name="message_index", methods={"GET"})
     */
    public function index(MessageRepository $messageRepository): Response
    {

        $messages = $messageRepository->findUserMessages($this->getUser('id'));
        return $this->render('message/index.html.twig', [
            'messages' => $messages,
        ]);
    }



    /**
     * @Route("/new", name="message_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $message = new Message();
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $message->setFromId($this->getUser());
            $message->setIsRead(0);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($message);
            $entityManager->flush();

            $toId = $form["to_id"]->getData()->getEmail();
            $firstName = $form["to_id"]->getData()->getFirstName();

            $mail = new Mail();
            $content = "Bonjour ".$firstName."<br/> Vous avez reçu un nouveau message sur Jobissim.";
            $mail->send($toId, $firstName, 'Nouveau message sur Jobissim.', $content);

            return $this->redirectToRoute('message_index');
        }

        return $this->render('message/new.html.twig', [
            'message' => $message,
            'form' => $form->createView(),
        ]);
    }


    
    /**
     * @Route("/{id}/edit", name="message_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Message $message): Response
    {
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('message_index');
        }

        return $this->render('message/edit.html.twig', [
            'message' => $message,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{letter}/{id}", name="message_show", methods={"GET","POST"})
     */
    public function show($id, $letter, Request $request, Message $message, MessageRepository $messageRepository, UserRepository $userRepo): Response
    {
        // dd($id);
        // $to = $userRepo->findOneBy(['id' => $id]);
        $messages = $messageRepository->Message($this->getUser('id'), $letter);
        // Ouvrir le message
        $message->setIsRead(1);

            $manager = $this->getDoctrine()->getManager();
            $manager->persist($message);
            $manager->flush();

        // Répondre au message
        $messageBack = new Message();
        $form = $this->createForm(ReplyMessageType::class, $messageBack);
        $form->handleRequest($request);
        $messagerie = $this->entityManager->getRepository(Message::class)->findOneBy(['id' => $id]);
        
        if ($messagerie instanceof Message) {
            $toId = $messagerie->getFromId();
            $sujet = $messagerie->getSubject();
        } 

        if ($form->isSubmitted() && $form->isValid()) {
            $messageBack->setFromId($this->getUser());
            $messageBack->setToId($toId);
            $messageBack->setSubject("Re : " . $sujet);
            $messageBack->setIsRead(0);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($messageBack);
            $entityManager->flush();

            return $this->redirectToRoute('message_index');
        }

        return $this->render('message/show.html.twig', [
            'message' => $message,
            'messageBack' => $messageBack,
            'form' => $form->createView(),
            'messages' => $messages
        ]);
    }



    /**
     * @Route("/{id}", name="message_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Message $message): Response
    {
        if ($this->isCsrfTokenValid('delete'.$message->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($message);
            $entityManager->flush();
        }

        return $this->redirectToRoute('message_index');
    }
}

templates/message/_delete_form.html.twig
<style>
.btn.btn-danger {
    height: 40px;
    width: 120px;
    font-size: 16px;
    font-weight: bold;
}

</style>

<form method="post" action="{{ path('message_delete', {'id': message.id}) }}" onsubmit="return confirm('Supprimer le message ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ message.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/message/_form.html.twig
<style>
.btn.btn-success {
    height: 40px;
    width: 120px;
}
</style>

{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Envoyer') }}</button>
{{ form_end(form) }}

templates/message/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer Message{% endblock %}

{% block body %}
    <h1>Editer le Message</h1>

    {{ include('message/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('message_index') }}">Boite de réception</a>

    {{ include('message/_delete_form.html.twig') }}
{% endblock %}

templates/message/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie{% endblock %}

{% block body %}

<style>
.btn.btn-primary, .btn.btn-danger {
    height: 40px;
    width: 120px;
}

.btn.btn-success, .btn.btn.btn-secondary {
    height: 60px;
    width: 150px;
}

.table {
    background: #f5f6f6;
}

</style>
    	<h2 class="font-weight-bold display-4 ">BOITE
		<span style="color: #2277ff">DE RÉCEPTION</span>
	</h2>
    <hr>

    <table class="table table-hover mt-5">
        <thead>
            <tr>
                <th>Sujet</th>
                <th>Éxpéditeur</th>
                <th>État</th>
                <th class="actionmess">Action</th>
                <th class="actionmess">Supprimer</th>
            </tr>
        </thead>
        <tbody>

        {% for message in messages %}
            <tr>
                <td><a style="color: black !important" href="{{ path('message_show', {'id': message.fromId.id, 'letter': message.id}) }}">{{ message.subject }}</a></td>
                <td>{{ message.fromId.firstname }} {{ message.fromId.lastname }}</td>
                {% if message.isRead == 0 %}
                <td><img src="{{ asset('img/mess.png') }}" alt="" width="50px"></td>
                {% else %}
                <td>ouvert</td>
                {% endif %}
                <td class="actionmess">
                    <a href="{{ path('message_show', {'id': message.id, 'letter': message.fromId.id}) }}"><button class="btn btn-primary">Lire</button></a>
                </td>
                <td class="actionmess">{{ include('message/_delete_form.html.twig') }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Boite de réception vide</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('message_new') }}"><button class="btn btn-success mt-4">Nouveau message</button></a>
{% endblock %}

templates/message/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Message{% endblock %}

{% block body %}

<style>
.btn.btn-primary {
    height: 60px;
    width: 150px;
}

.btn.btn-success, .btn.btn.btn-secondary {
    height: 60px;
    width: 150px;
}
</style>


    	<h2 class="font-weight-bold display-4 ">NOUVEAU
		<span style="color: #2277ff">MESSAGE</span>
	</h2>
    <hr>

    <div class="newform">
        {{ include('message/_form.html.twig') }}
    </div>

    <a href="{{ path('message_index') }}"><button class="btn btn-info mt-3">Boite de réception</button></a>
{% endblock %}

templates/message/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Message{% endblock %}

{% block body %}
<style>
.btn.btn-primary {
    height: 40px;
    width: 120px;
}

.btn.btn-success, .btn.btn.btn-secondary {
    height: 40px;
    width: 120px;
}

h5 {
    font-size: 20px;
    font-weight: bold;
    text-transform: uppercase;
    margin-top: 2%;
}

.date {
    display: flex;
    flex-direction: row;
    align-items: center;
    color: #000000a1;
    font-size: 13px;
    font-weight: 600;
    margin-bottom: 2%;
}

.fromid {
    display: flex;
    flex-direction: column;
}

.fa-clock {
    color: #000000a1;
    font-size: 14px;
}

.fa-file-pdf {
    color: black;
    font-size: 20px;
    margin-right: 1%;
}

.fa-file-pdf:hover {
    transform: scale(1.1);
}

h6 {
    font-size: 12px;
    color: #000000a1;
    font-weight: 600;
}

.bbtn {
    display: flex;
    flex-direction: row;
    align-items: center;
    margin-top: 2%;
}

.changepassword2 {
    font-size: 13px;
    text-transform: uppercase;
    color: black !important;
}

.infocv {
    font-size: 11px;
}

</style>

    	<h2 class="font-weight-bold display-4 ">MON
		<span style="color: #2277ff">MESSAGE</span>
	</h2>
    <hr>


    {# {% for message in messages %} #}


        <div class="newform">
        
            <div class="headermess">
                <img class="mr-3" src="/uploads/{{ message.fromId.image }}" alt="" width="65px"> 
                <div class="fromid">
                    <strong>{{message.fromId.firstname}} {{message.fromId.lastname}}</strong>
                    <h6>{{message.fromId}}</h6>
                </div>

            </div>

            <hr>

            <div class="bodymess">

                <h5>{{message.subject}}</h5>

                <div class="date">
                    <i class="far fa-clock mr-2"></i> le : {{ message.createdAt ? message.createdAt|date('d-m-Y, à H:i:s') : '' }}
                </div>
                
                <p class="mt-4">{{message.content}}</p>
                
                {% if message.fichier %}
                <a class="changepassword2 mt-5" href="/uploads/{{ message.fichier }}" download><i class="fas fa-file-pdf"></i>Pièce jointe</a>
                {% endif %}

                {% if message.cv != '' %}
                <a class="changepassword2 mt-2" href="/uploads/{{ message.cv }}" download><i class="fas fa-file-pdf"></i>Télécharger le cv</a>
                {% else %} 
                    <p class="infocv mt-2">Information : l'utilisateur n'a pas déposé son cv</p>
                {% endif %}

            </div>

        
        </div>

        <hr>

    {# {% endfor %} #}

        <div class="newform mt-1">
        {{ include('message/_form.html.twig') }}
    </div>

<div class="bbtn">
    <a href="{{ path('message_index') }}"><button class="btn btn-primary mr-2">Réception</button></a>
    {{ include('message/_delete_form.html.twig') }}
</div>

{% endblock %}